#!/bin/bash -

bitrate=320

for flacfile; do
  mp3file=${flacfile/.flac/.mp3}

#  ARTIST=$(metaflac "$flacfile" --show-tag=ARTIST | sed s/.*=//g)
#  TITLE=$(metaflac "$flacfile" --show-tag=TITLE | sed s/.*=//g)
#  ALBUM=$(metaflac "$flacfile" --show-tag=ALBUM | sed s/.*=//g)
#  GENRE=$(metaflac "$flacfile" --show-tag=GENRE | sed s/.*=//g)
#  TRACKNUMBER=$(metaflac "$flacfile" --show-tag=TRACKNUMBER | sed s/.*=//g)
#  DATE=$(metaflac "$flacfile" --show-tag=DATE | sed s/.*=//g)

  if [ "$mp3file" != "$flacfile" ]; then
    duration=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 -sexagesimal "$flacfile" | sed 's/\.[0-9]*$//')
    printf 'Converting %s (%s) to %s ...\n' "$flacfile" "$duration" "$mp3file"
    flac -dc "$flacfile" | lame -b "$bitrate" - "$mp3file"
  fi
done
