#!/bin/bash

base=$(basename -- "$0")
if [ $# -eq 0 ]; then
  printf >&2 "Usage: %s image ...\n" "$base"
  exit 1
fi

for file; do
  jpg=${file%.*}.jpg
  if [[ -f $jpg ]]; then
    printf >&2 "'%s' exists already, skipping.\n" "$jpg"
  elif [[ $jpg != $file ]]; then
    ext=${file##*.}
    ext=${ext,,}
    if [[ $ext == 'heic' ]]; then
      printf "%s: %s -> %s\n" "$base" "$file" "$jpg"
      heif-convert "$file" "$jpg" >/dev/null && touch -r "$file" "$jpg"
    elif [ -f "$jpg" ]; then
      printf >&2 "%s: %s exists, not overwriting.\n" "$base" "$jpg"
    else
      printf "%s: %s -> %s\n" "$base" "$file" "$jpg"
      convert "$file" "$jpg" && touch -r "$file" "$jpg"
    fi
  else
    printf >&2 "%s: '%s' already has 'jpg' extension, skipping.\n" "$base" "$file"
  fi
done

