#!/bin/bash

if [ $# -eq 0 ]; then
  cat >&2 <<EOF
Usage:
  $(basename -- "$0") file ...

Split an Yle Arena MKV file into an MP4 and an SRT file.
EOF
  exit 1
fi

for file; do
  if [[ $file != *.mkv ]]; then
    echo >&2 "Skipping ${file}, extension must be .mkv."
    continue
  fi
  base=${file%.mkv}

  # convert videu/audio to mp4
  mp4file="${base}.mp4"
  ffmpeg -y -i "$file" -codec copy "$mp4file"

  # extract subtitles (if present)
  srttrack=$(LANG=C mkvmerge -i "$file" | perl -ne 'print $1 if /Track ID (\d+): subtitles/')
  if [ -n "$srttrack" ]; then
    srtfile="${base}.srt"
    mkvextract tracks "$file" "${srttrack}:${srtfile}"
  fi
done
