#!/usr/bin/perl

use strict;
use warnings;
use File::Basename;

die "Usage: ".(basename $0)." file ...\n" unless @ARGV;

foreach my $file (@ARGV) {
  #open INFO, "identify -verbose $file |" or die "couldn't open pipe: $!\n";
  open INFO, "exiftool -DateTimeOriginal $file |" or die "couldn't open pipe: $!\n";
  while (<INFO>) {
    #if (/Exif:DateTimeOriginal: (\d\d\d\d):(\d\d):(\d\d) (\d\d):(\d\d):(\d\d)/) {
    if (/(\d\d\d\d):(\d\d):(\d\d) (\d\d):(\d\d):(\d\d)/) {
      warn "$file -> $1-$2-$3 $4:$5:$6\n";
      system("touch", "--date=$1-$2-$3 $4:$5:$6", $file);
      last;
    }
  }
  close INFO;
}
