#!/usr/bin/perl

use strict;
use warnings;
use File::Basename;

die "Usage: ".(basename $0)." file ...\n" unless @ARGV;

foreach my $file (@ARGV) {
  if ($file =~ /(20\d\d)(\d\d)(\d\d)\D(\d\d)(\d\d)(\d\d)/) {
    my ($y, $mon, $d, $hr, $min, $sec) = ($1, $2, $3, $4, $5, $6);
    if ($hr < 24 && $min < 60 && $sec < 60) {
      system("touch", "--date=${y}-${mon}-${d}T${hr}:${min}:${sec}", $file);
    } else {
      system("touch", "--date=${y}-${mon}-${d}", $file);
    }
  } elsif ($file =~ /(20\d\d)(\d\d)(\d\d)\D(\d\d)(\d\d)/) {
    my ($y, $mon, $d, $hr, $min, $sec) = ($1, $2, $3, $4, $5, 0);
    if ($hr < 24 && $min < 60 && $sec < 60) {
      system("touch", "--date=${y}-${mon}-${d}T${hr}:${min}:${sec}", $file);
    } else {
      system("touch", "--date=${y}-${mon}-${d}", $file);
    }
  } elsif ($file =~ /(20\d\d)(\d\d)(\d\d)-..-(\d\d)(\d\d)(\d\d)/) {
    my ($y, $mon, $d, $hr, $min, $sec) = ($1, $2, $3, $4, $5, $6);
    if ($hr < 24 && $min < 60 && $sec < 60) {
      system("touch", "--date=${y}-${mon}-${d}T${hr}:${min}:${sec}", $file);
    } else {
      system("touch", "--date=${y}-${mon}-${d}", $file);
    }
  } elsif ($file =~ /(20\d\d)(\d\d)(\d\d)-..-(\d\d)(\d\d)/) {
    my ($y, $mon, $d, $hr, $min, $sec) = ($1, $2, $3, $4, $5);
    if ($hr < 24 && $min < 60 && $sec < 60) {
      system("touch", "--date=${y}-${mon}-${d}T${hr}:${min}:${sec}", $file);
    } else {
      system("touch", "--date=${y}-${mon}-${d}", $file);
    }
  } elsif ($file =~ /(20\d\d)-?(\d\d)-?(\d\d)/) {
    my ($y, $m, $d) = ($1, $2, $3);
    system("touch", "--date=$y-$m-$d", $file);
  } else {
    warn "No date found in '$file'.\n";
  }
}
