#!/bin/bash

if [ $# -eq 0 ]; then
  echo >&2 "Usage: $(basename $0) file ..."
  exit 1
fi

for file; do
  mp4="${file%.*}.mp4"
  if [[ $mp4 != $file ]]; then
    duration=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 -sexagesimal "$file" | sed 's/\.[0-9]*$//')
    printf 'Converting %s (%s) ...\n' "$file" "$duration"
    ffmpeg -loglevel warning -stats -i "$file" "$mp4" && touch -r "$file" "$mp4"
  else
    echo "'$file' already has 'mp4' extension (skipping)."
  fi
done
