#!/bin/bash -

if [ $# -eq 0 ]; then
  echo >&2 "Usage: $(basename $0) wavfile ..."
  exit 1
fi

for wav; do
  mp3="${wav%.wav}.mp3"
  duration=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 -sexagesimal "$wav" | sed 's/\.[0-9]*$//')
  printf 'Converting %s (%s) to %s ...\n' "$wav" "$duration" "$mp3"
  ffmpeg -loglevel warning -stats -i "$wav" "$mp3"
done
